### ISSUE TITLE
Wider custom logo on mobiles under 400 screen width

### ISSUE THREAD

**Issue by mP-wiki** [giterlizzi/dokuwiki-template-bootstrap3#380]
### Description
I'm customizing Bootstrap3 theme (dokuwiki logo) logo to suit the wiki (myPlace.wiki) and I could adjust the codes (bootstrap.mini.css) and fit inside navbar for all devices except those mostly iPhones (under screen width 400)
[Description of the bug or feature]
Not a bug - customization
I donno where to add the code for, if I add a smaller logo image. I have to set 'height' of logo in tpl_navbar.php to '64' to get it bogger for @media min-width 768. Otherwise logo in desktop/laptop is so small. Then I could adjust bootstrap.mini.css to fit all other mobile devices including tablets and mobiles with width >400. If I can add a smaller logo for devices max-width 400 where to add code. Is it possible to add code on tpl_navbar.php? 
### Steps to reproduce
1. Go to myPlace.wiki -> 
2. Google chome -> 
3. Developer tools/right click & inspect the page ->
4. Toggle device toolbar -> 
5. Change to one of those devices with width <400 , eg: iPhoneX.

**Expected behavior:** [What you expected to happen]
Logo to fit inside navbar table

**Actual behavior:** [What actually happened]
Logo go outside the table. 

### Versions
* [Bootstrap3 Template]
* [DokuWiki] - Greebo
* [Browser] - Google Chrome

### Screenshots or Logs
Can add if needed
[Paste your logs or attach the screenshot]

### Sample page or snippet
https://myplace.wiki/home

**Comment by LotarProject** [comment]
Hi, thanks for using my template ;)

I suggest to don't modify the `bootstrap.min.css` (and `tpl_navbar.php`) file because everything manual changes will be lost on every template upgrade.

You can use `userstyle.css` (or `userall.css`) file placed in `<dokuwiki>/conf` directory to customize the template. For more information: https://www.dokuwiki.org/devel:css

At your disposal,
Joseph

**Comment by mP-wiki** [comment]
@LotarProject . I tried adding the codes to change logo size for media with max-width 400 (all other screen sizes the logo size entered in tpl_navbar.php is good) but not doing anything - tested in google chrome developer tools. Could you tell me how to add the custom logo size in userstyle.css please..

**Comment by mP-wiki** [comment]
@LotarProject  Do I need to add the theme reference like 

`body.default #dw__logo`

 in userstyle.css ? as mentioned [here ](https://www.dokuwiki.org/template:bootstrap3)

**Comment by mP-wiki** [comment]
@LotarProject - you gonna do any help? If not I will try some other template?

**Comment by MvErven** [comment]
Hello mP-wiki. Maybe the advanced configuration utility can help (same author) There it's possible to change the userstyle.css too. 

In my opinion you don't need to copy the entire css. Only the part you wish to alter. I (or my company) doesn't support this wiki on mobiles, so I never had anything for the logo. 

I can imagine you need something with height= and width=
ps. (Your site looks nice!)

**Comment by mP-wiki** [comment]
@MvErven ,  Thanks for the help... So jumbotron will override the default css for mobile displays?

**Comment by MvErven** [comment]
Hi, Well I am using this template for one year now. I must say it works. but sometimes I change the layout and use another Tag. pannels, acordeon, Text and so on. never had the need for jumbotron. but I can imagine you may give it a try. wouldn't it be nice if it works. good luck. cheers. 



Verzonden vanaf mobielOn mP-wiki <notifications@github.com>, 11 Aug 2018 11:50 am wrote:@MvErven ,  Thanks for the help... So jumbotron will override the default css for mobile displays?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LotarProject/dokuwiki-template-bootstrap3","title":"LotarProject/dokuwiki-template-bootstrap3","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/LotarProject/dokuwiki-template-bootstrap3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mP-wiki in #380: @MvErven ,  Thanks for the help... So jumbotron will override the default css for mobile displays? "}],"action":{"name":"View Issue","url":"https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-412264468"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-412264468",
"url": "https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-412264468",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [LotarProject/dokuwiki-template-bootstrap3] Wider custom logo on mobiles under 400 screen width (#380)",
"sections": [
{
"text": "",
"activityTitle": "**mP-wiki**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mP-wiki",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"LotarProject/dokuwiki-template-bootstrap3\",\n\"issueId\": 380,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"LotarProject/dokuwiki-template-bootstrap3\",\n\"issueId\": 380\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-412264468"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344371422\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mP-wiki** [comment]
@MvErven . Thank you. I will try and will post here if i get it fixed. Thanks friend, you are a star where others are a tar....

**Comment by MvErven** [comment]
You're welcome. Thank you for your compliments.  Wish you all the best.



Verzonden vanaf mobielOn mP-wiki <notifications@github.com>, 13 Aug 2018 2:38 pm wrote:@MvErven . Thank you. I will try and will post here if i get it fixed. Thanks friend, you are a star where others are a tar....

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LotarProject/dokuwiki-template-bootstrap3","title":"LotarProject/dokuwiki-template-bootstrap3","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/LotarProject/dokuwiki-template-bootstrap3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mP-wiki in #380: @MvErven . Thank you. I will try and will post here if i get it fixed. Thanks friend, you are a star where others are a tar.... "}],"action":{"name":"View Issue","url":"https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-412503651"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-412503651",
"url": "https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-412503651",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [LotarProject/dokuwiki-template-bootstrap3] Wider custom logo on mobiles under 400 screen width (#380)",
"sections": [
{
"text": "",
"activityTitle": "**mP-wiki**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mP-wiki",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"LotarProject/dokuwiki-template-bootstrap3\",\n\"issueId\": 380,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"LotarProject/dokuwiki-template-bootstrap3\",\n\"issueId\": 380\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-412503651"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344371422\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by MvErven** [comment]
@mP-wiki  I have looked at your site. I would like to give more advice about your configuration. For instance: some buttons being non functional and some settings. How can I reach you?

**Comment by mP-wiki** [comment]
> @mP-wiki I have looked at your site. I would like to give more advice about your configuration. For instance: some buttons being non functional and some settings. How can I reach you?

OK. Non-functional buttons? Left side menu - its bcoz those pages not created yet. Could you elaborate? I can add an account if you like to join there. I won't open to public until site is full ready and email system sorted. Thank you @MvErven

**Comment by MvErven** [comment]
@mP-wiki  That would be great! I think there are some configuration settings which may need tweaking. Especially in the bootswrapper template. Also we can have a look at you mail settings (smtpmail is the plugin to use, but in latest download added by default) I believe you and I can get this thing to work.

**Comment by mP-wiki** [comment]
> @mP-wiki That would be great! I think there are some configuration settings which may need tweaking. Especially in the bootswrapper template. Also we can have a look at you mail settings (smtpmail is the plugin to use, but in latest download added by default) I believe you and I can get this thing to work.

I have enabled ur account and sent an email. Did you receive it. Sorry for delay in responding... @MvErven

**Comment by MvErven** [comment]
Yes, I have received your email. I will have a look this week. It will be mostly in the evening here. talk to you soon. 



Verzonden vanaf mobielOp mP-wiki <notifications@github.com>, schreef 12 nov. 2018 2:42 a.m.:
@mP-wiki That would be great! I think there are some configuration settings which may need tweaking. Especially in the bootswrapper template. Also we can have a look at you mail settings (smtpmail is the plugin to use, but in latest download added by default) I believe you and I can get this thing to work.

I have enabled ur account and sent an email. Did you receive it. Sorry for delay in responding... @MvErven

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LotarProject/dokuwiki-template-bootstrap3","title":"LotarProject/dokuwiki-template-bootstrap3","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/LotarProject/dokuwiki-template-bootstrap3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mP-wiki in #380: \u003e @mP-wiki That would be great! I think there are some configuration settings which may need tweaking. Especially in the bootswrapper template. Also we can have a look at you mail settings (smtpmail is the plugin to use, but in latest download added by default) I believe you and I can get this thing to work.\r\n\r\nI have enabled ur account and sent an email. Did you receive it. Sorry for delay in responding... @MvErven "}],"action":{"name":"View Issue","url":"https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-437727359"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-437727359",
"url": "https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-437727359",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [LotarProject/dokuwiki-template-bootstrap3] Wider custom logo on mobiles under 400 screen width (#380)",
"sections": [
{
"text": "",
"activityTitle": "**mP-wiki**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mP-wiki",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"LotarProject/dokuwiki-template-bootstrap3\",\n\"issueId\": 380,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"LotarProject/dokuwiki-template-bootstrap3\",\n\"issueId\": 380\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/380#issuecomment-437727359"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344371422\n}"
}
],
"themeColor": "26292E"
}
]
