### ISSUE TITLE
Missing Header Icons

### ISSUE THREAD

**Issue by elo91** [giterlizzi/dokuwiki-template-bootstrap3#468]
Hi,

Missing icons on all webpages

  
![icone](https://user-images.githubusercontent.com/63399806/78885705-5b44bc80-7a5d-11ea-8ee5-79dc3914d169.png)

Versions:

[Bootstrap3 Template] : Template v2020-04-04 (hotfix/20200406)
[DokuWiki] : Release 2018-04-22a "Greebo" (From Debian repository)
[PHP] : 7.3.14
[Browser] : Chrome

I downloaded the package and unzipped it in /var/lib/dokuwiki/lib/tpl/bootstrap3.

The logs:
```
[Thu Apr 09 12:08:15.631801 2020] [php7:warn] [pid 13835] [client XX.XX.XX.XX:19159] PHP Warning:  require_once(/var/lib/dokuwiki/lib/tpl/bootstrap3/../../../vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/dokuwiki/inc/init.php on line 185, referer: https://mywiki.com/doku.php
[Thu Apr 09 12:08:15.632120 2020] [php7:error] [pid 13835] [client XX.XX.XX.XX:19159] PHP Fatal error:  require_once(): Failed opening required '/var/lib/dokuwiki/lib/tpl/bootstrap3/../../../vendor/autoload.php' (include_path='.:/usr/share/php') in /usr/share/dokuwiki/inc/init.php on line 185, referer: https://mywiki.com/doku.php
```
Thank you

**Comment by jomority** [comment]
I have a similar error with other icons. It looks like it has something to do with iconify:

```
2020/04/15 15:40:15 [error] 18759#18759: *2414 open() "/var/www/dokuwiki/lib/tpl/bootstrap3/lib/tpl/bootstrap3/data/cache/7/71f1afb2b16f383446a096b1aaeba92d.js" failed (2: No such file or directory), request: "GET /lib/tpl/bootstrap3/iconify.php?icon=mdi-earth-arrow-right.svg&color=%23666666 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock"
```

A workaround for me is to create symlinks in the bootstrap3 folder:
```
sudo ln -s ../../../data /var/www/dokuwiki/lib/tpl/bootstrap3/data
sudo ln -s ../../../lib /var/www/dokuwiki/lib/tpl/bootstrap3/lib
```

**Comment by tarasis** [comment]
Also getting this issue. Wondering if its partly because of how Arch puts files in different places.

``/usr/share/webapps/dokuwiki`` is the main dir, with ``lib/tpl`` and ``lib/plugins`` pointing to ``/var/lib/dokuwiki`` 

There is no ``/var/lib/dokuwiki/tpl/bootstrap3/../../../inc/init.php`` file there, or rather there is, but its not accessible with ../../../ even on the command line

`
[rob@backup bootstrap3]$ pwd
/usr/share/webapps/dokuwiki/lib/tpl/bootstrap3
[rob@backup bootstrap3]$ less ../../../inc/in
indexer.php    infoutils.php  init.php
[rob@backup bootstrap3]$ less ../../../inc/init.php
../../../inc/init.php: No such file or directory

--- directly referencing the file works

[rob@backup bootstrap3]$ cat /usr/share/webapps/dokuwiki/inc/init.php
<?php
/**
 * Initialize some defaults needed for DokuWiki
 */
******** I removed the rest *********
`

Below is error from the web server: 
`[ERROR 0 /lib/tpl/bootstrap3/iconify.php] PHP message: PHP Warning:  require_once(): open_basedir restriction in effect. File(/var/lib/dokuwiki/tpl/bootstrap3/../../../inc/init.php) is not within the allowed path(s): (/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/etc/webapps/dokuwiki/:/var/lib/dokuwiki/:/srv/wiki:/var/lib/dokuwiki/tpl/bootstrap3/) in /var/lib/dokuwiki/tpl/bootstrap3/iconify.php on line 37
PHP message: PHP Warning:  require_once(/var/lib/dokuwiki/tpl/bootstrap3/../../../inc/init.php): failed to open stream: Operation not permitted in /var/lib/dokuwiki/tpl/bootstrap3/iconify.php on line 37
PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/lib/dokuwiki/tpl/bootstrap3/../../../inc/init.php' (include_path='.:') in /var/lib/dokuwiki/tpl/bootstrap3/iconify.php on line 37`

**Comment by tarasis** [comment]
Editing iconify.php to change DOKU_INC from

`
if (!defined('DOKU_INC')) {
    define('DOKU_INC', dirname(__FILE__) . '/../../../');
}
`

to

`
if (!defined('DOKU_INC')) {
    define('DOKU_INC', '/usr/share/webapps/dokuwiki');
}
`
allowed the icons to load properly.

**Comment by giterlizzi** [comment]
Thanks @tarasis @jomority. In develop branch have added a support for different DokuWiki installation:
* Bitnami
* Debian / Ubuntu
* Arch Linux
* custom path via ``doku_inc.php`` PHP script

**Comment by thoschworks** [comment]
I use the [linuxserver/docker-dokuwiki](https://github.com/linuxserver/docker-dokuwiki) image (cause it has support for ARM platforms) and have the same problems.

Is it possible to add support for this image?

**Comment by thoschworks** [comment]
Oooops, it is already implemented in the develop branch. 😊 

I looked only in https://github.com/giterlizzi/dokuwiki-template-bootstrap3/commit/fb417298329fa79f3ea74c349c816ed78c3da522, but it is an outdated version…

After installing the development version all icons are at their place. 👍
