### ISSUE TITLE
Template  does not seem to work after selection

### ISSUE THREAD

**Issue by jprzywieczerski** [giterlizzi/dokuwiki-template-bootstrap3#568]
### Description

Template does not affect DokuWiki pages (see screenshot bellow)

### Steps to reproduce

Install and select Bootstrap3 Template

### Versions

* Bootstrap3 Template - 2022-07-27
* [DokuWiki  "Igor"
* [PHP 8.1.6]
* Any

### Screenshots or Logs

![boostrap](https://user-images.githubusercontent.com/77389613/189693953-8b3b9282-7dfe-4db5-80cc-2c7daec5884a.png)

**Comment by giterlizzi** [comment]
You have errors in apache error_log or in JS console ? 

Joseph

**Comment by castn** [comment]
I experienced the same issue, and it looked exactly the same as in the above screenshot. I was running dokuwiki in a container. After I installed the template, I installed the bootstrap plugin, which adds support for bootstrap. I installed it, because I needed it. Not sure if it is required for the template. After I restarted dokuwiki I got the theme successfully displayed.
